CREATE DATABASE IF NOT EXISTS brain CHARACTER SET = utf8 COLLATE = utf8_bin;
USE brain;

CREATE TABLE IF NOT EXISTS `users`
(
  user_id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'user id',
  username VARCHAR(30) NOT NULL COMMENT 'login',
  password VARCHAR(30) NOT NULL COMMENT 'password',
  role_id INT(11) DEFAULT '2' NOT NULL COMMENT 'user role'
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `roles`
(
  user_id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'role id',
  role VARCHAR(30) NOT NULL COMMENT 'role'
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `user_ad_ref` (
    user_id INT(11) NOT NULL COMMENT 'user id',
    ad_id INT(11) NOT NULL COMMENT 'ad id'
)